[package]
authors = [
  "KeYang Hu <keyang.hu@qq.com>",
  "Mingxian Su <aarkegz@gmail.com>",
]
categories = ["embedded", "no-std"]
description = "ArceOS-Hypervisor riscv vcpu module"
edition = "2024"
keywords = ["hypervisor", "vcpu", "riscv"]
license = "Apache-2.0 OR MIT"
name = "riscv_vcpu_te"
repository = "https://github.com/bullhh/riscv_vcpu_te"
version = "0.1.0"


[dependencies]
log = "0.4.19"
cfg-if = "1.0"
bitflags = "2.2"
bit_field = "0.10"
crate_interface = "0.1"

riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
riscv-decode = { git = "https://github.com/KuangjuX/riscv-decode.git" }
rustsbi = { version = "0.4.0", features = ["forward"] }
sbi-rt = { version = "0.0.3", features = ["integer-impls"] }
sbi-spec = { version = "0.0.7", features = ["legacy"] }
tock-registers = "0.9"
memoffset = { version = ">=0.6.5", features = ["unstable_const"] }

axerrno = "0.1.0"
page_table_entry = "0.5"
memory_addr = "0.4"

axaddrspace = { git = "https://github.com/arceos-hypervisor/axaddrspace.git" }
axvcpu = { git = "https://github.com/arceos-hypervisor/axvcpu.git" }
axvisor_api = { git = "https://github.com/arceos-hypervisor/axvisor_api.git"}